# Generated by Django 4.0.4 on 2022-05-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroomgmt.club'),
        ),
    ]
