# Generated by Django 4.0.4 on 2022-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomgmt', '0005_alter_club_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
